# Generated by Django 4.2.8 on 2025-12-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.IntegerField(default=554)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('rtsp_path', models.CharField(blank=True, help_text='e.g., /stream1', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline'), ('error', 'Error')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('resolution_width', models.IntegerField(default=1920)),
                ('resolution_height', models.IntegerField(default=1080)),
                ('fps', models.IntegerField(default=30, help_text='Frames per second')),
                ('location', models.CharField(blank=True, help_text='e.g., Main Hall, Lab 1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cameras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique room name', max_length=255, unique=True)),
                ('camera_ip', models.CharField(help_text='Camera IP address or URL', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(blank=True, help_text='Last time counts were updated', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='camera_room_name_144347_idx'), models.Index(fields=['-created_at'], name='camera_room_created_71e8f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CameraCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.IntegerField(default=0)),
                ('frames_processed', models.IntegerField(default=0)),
                ('inference_time_ms', models.FloatField(default=0.0, help_text='Average inference time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='camera.camera')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='camera.room')),
            ],
            options={
                'verbose_name_plural': 'Camera Counts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['camera', '-timestamp'], name='camera_came_camera__20b758_idx'), models.Index(fields=['room', '-timestamp'], name='camera_came_room_id_724ec9_idx')],
            },
        ),
    ]
